/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useMemo, useState } from "react";
import { Button, Checkbox, Form, Input, Modal, Popconfirm, Select, Space, Table, Tag } from "antd";
import { PlusOutlined } from "@ant-design/icons";
type View="personnel"|"permissions"|"organization";
type Person={id:string;code:string;name:string;org:string;role:string;contact:string;status:string};
type Org={id:string;title:string;type:string;leader:string;count:number;status:string;parent?:string};
type Perm={id:string;role:string;scope:string;mods:string[]};
const modules=["仪表盘","生产管理","物料管理","模具管理","质量与追溯","生产报表","基础数据","系统管理"];
const seedPeople:Person[]=[{id:"u1",code:"E001",name:"张伟",org:"注塑车间",role:"班组长",contact:"138****1001",status:"在职"},{id:"u2",code:"E002",name:"李娜",org:"质量部",role:"质量工程师",contact:"li.na@example.com",status:"在职"}];
const seedOrg:Org[]=[{id:"o1",title:"泰国工厂",type:"工厂",leader:"王强",count:86,status:"启用"},{id:"o2",title:"注塑车间",type:"部门",leader:"赵敏",count:32,status:"启用",parent:"o1"},{id:"o3",title:"A班组",type:"班组",leader:"张伟",count:12,status:"启用",parent:"o2"}];
const seedPerm:Perm[]=[{id:"r1",role:"管理员",scope:"全工厂",mods:modules},{id:"r2",role:"生产主管",scope:"生产车间",mods:["生产管理","物料管理","模具管理"]},{id:"r3",role:"质量人员",scope:"质量部",mods:["质量与追溯","生产报表"]}];
const pageTitles={personnel:"人员管理",permissions:"权限管理",organization:"组织管理"};
export function SystemManagementView({view}:{view:View}){const [people,setPeople]=useState(seedPeople),[orgs,setOrgs]=useState(seedOrg),[perms,setPerms]=useState(seedPerm),[editing,setEditing]=useState<any>(null),[form]=Form.useForm();
 useEffect(()=>{for(const [k,set] of [["people",setPeople],["orgs",setOrgs],["perms",setPerms]] as const){try{const v=localStorage.getItem("mes-system-"+k);if(v)(set as any)(JSON.parse(v));}catch{}}},[]); useEffect(()=>{localStorage.setItem("mes-system-people",JSON.stringify(people))},[people]);useEffect(()=>{localStorage.setItem("mes-system-orgs",JSON.stringify(orgs))},[orgs]);useEffect(()=>{localStorage.setItem("mes-system-perms",JSON.stringify(perms))},[perms]);
 const open=(row:any={})=>{setEditing(row);form.setFieldsValue(row.id?row:{status:view==="personnel"?"在职":"启用",type:"部门",mods:[]})}; const save=(v:any)=>{const id=editing.id||crypto.randomUUID(); if(view==="personnel")setPeople(x=>editing.id?x.map(r=>r.id===id?{...r,...v}:r):[...x,{...v,id}]); else if(view==="organization")setOrgs(x=>editing.id?x.map(r=>r.id===id?{...r,...v,count:Number(v.count||0)}:r):[...x,{...v,id,count:Number(v.count||0)}]); else setPerms(x=>editing.id?x.map(r=>r.id===id?{...r,...v}:r):[...x,{...v,id}]);setEditing(null)};
 const orgOptions=orgs.map(o=>({value:o.title,label:o.title}));
 const parentOrgOptions=orgs.map(o=>({value:o.id,label:o.title}));
 const roleOptions=perms.map(p=>({value:p.role,label:p.role}));
 if(view==="permissions")return <><p className="mes-notice">配置演示，不代表已启用登录鉴权</p><div className="table-toolbar"><strong>角色权限</strong><Button type="primary" icon={<PlusOutlined/>} onClick={()=>open()}>新增角色</Button></div><Table rowKey="id" dataSource={perms} pagination={{pageSize:10,showSizeChanger:true}} columns={[{title:"角色",dataIndex:"role"},{title:"数据范围",dataIndex:"scope"},{title:"模块权限",dataIndex:"mods",render:(m:string[])=><Space wrap>{m.map(x=><Tag key={x}>{x}</Tag>)}</Space>},{title:"操作",render:(_:unknown,r:Perm)=><Button type="link" onClick={()=>open(r)}>编辑</Button>}]}/><Editor view={view} editing={editing} form={form} onSave={save} onClose={()=>setEditing(null)} orgOptions={orgOptions} roleOptions={roleOptions} parentOrgOptions={parentOrgOptions}/> </>;
 const cols=view==="personnel"?[{title:"工号",dataIndex:"code"},{title:"姓名",dataIndex:"name"},{title:"组织",dataIndex:"org"},{title:"岗位角色",dataIndex:"role"},{title:"电话 / 邮箱",dataIndex:"contact"},{title:"状态",dataIndex:"status",render:(v:string)=><Tag color="green">{v}</Tag>},{title:"操作",render:(_:unknown,r:Person)=><Actions onEdit={()=>open(r)} onDelete={()=>setPeople(x=>x.filter(p=>p.id!==r.id))} label="人员"/>}]:[{title:"名称",dataIndex:"title"},{title:"类型",dataIndex:"type"},{title:"负责人",dataIndex:"leader"},{title:"人数",dataIndex:"count"},{title:"状态",dataIndex:"status",render:(v:string)=><Tag color="green">{v}</Tag>},{title:"操作",render:(_:unknown,r:Org)=><Actions onEdit={()=>open(r)} onDelete={()=>setOrgs(x=>x.filter(o=>o.id!==r.id))} label="组织"/>}];
 const data=view==="personnel"?people:orgs; return <><p className="mes-notice">配置演示，不代表已启用登录鉴权</p><div className="table-toolbar"><strong>{pageTitles[view]}</strong><Button type="primary" icon={<PlusOutlined/>} onClick={()=>open()}>新增{view==="personnel"?"人员":"组织"}</Button></div>{view==="personnel"?<PersonnelTable people={people} columns={cols} orgOptions={orgOptions} roleOptions={roleOptions}/>:<Table rowKey="id" dataSource={treeOrgs(data as Org[])} columns={cols as any} pagination={{pageSize:10,showSizeChanger:true}}/>}<Editor view={view} editing={editing} form={form} onSave={save} onClose={()=>setEditing(null)} orgOptions={orgOptions} roleOptions={roleOptions} parentOrgOptions={parentOrgOptions}/></>}
 function treeOrgs(items:Org[]){return items.filter(x=>!x.parent).map(x=>({...x,children:items.filter(y=>y.parent===x.id).map(y=>({...y,children:items.filter(z=>z.parent===y.id)}))}))}
 function Actions({onEdit,onDelete,label}:{onEdit:()=>void;onDelete:()=>void;label:string}){return <Space><Button type="link" onClick={onEdit}>编辑</Button><Popconfirm title={`确认删除${label}？`} onConfirm={onDelete}><Button type="link" className="mes-destructive-action">删除</Button></Popconfirm></Space>}
 function PersonnelTable({people,columns,orgOptions,roleOptions}:{people:Person[];columns:any[];orgOptions:any[];roleOptions:any[]}){const[q,setQ]=useState(""),[org,setOrg]=useState<string>(),[role,setRole]=useState<string>(),[status,setStatus]=useState<string>();const rows=useMemo(()=>people.filter(p=>(!q||Object.values(p).join(" ").includes(q))&&(!org||p.org===org)&&(!role||p.role===role)&&(!status||p.status===status)),[people,q,org,role,status]);return <><Space className="table-toolbar" wrap><Input.Search placeholder="搜索工号、姓名、联系方式" allowClear onChange={e=>setQ(e.target.value)} style={{width:260}}/><Select allowClear placeholder="组织" onChange={setOrg} options={orgOptions}/><Select allowClear placeholder="角色" onChange={setRole} options={roleOptions}/><Select allowClear placeholder="状态" onChange={setStatus} options={["在职","停用"].map(x=>({value:x,label:x}))}/></Space><Table rowKey="id" dataSource={rows} columns={columns} pagination={{pageSize:10,showSizeChanger:true}}/></>}
 function Editor({view,editing,form,onSave,onClose,orgOptions,roleOptions,parentOrgOptions}:{view:View;editing:any;form:any;onSave:(v:any)=>void;onClose:()=>void;orgOptions:any[];roleOptions:any[];parentOrgOptions:any[]}){return <Modal open={!!editing} title={editing?.id?"编辑":"新增"} onCancel={onClose} onOk={()=>form.submit()}><Form form={form} layout="vertical" onFinish={onSave}>{view==="personnel"?<><Form.Item name="code" label="工号" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="name" label="姓名" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="org" label="组织"><Select options={orgOptions}/></Form.Item><Form.Item name="role" label="岗位角色"><Select options={roleOptions}/></Form.Item><Form.Item name="contact" label="电话 / 邮箱"><Input/></Form.Item><Form.Item name="status" label="状态"><Select options={["在职","停用"].map(x=>({value:x,label:x}))}/></Form.Item></>:view==="organization"?<><Form.Item name="title" label="名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="type" label="类型"><Select options={["工厂","部门","班组"].map(x=>({value:x,label:x}))}/></Form.Item><Form.Item name="parent" label="父级组织"><Select allowClear options={parentOrgOptions}/></Form.Item><Form.Item name="leader" label="负责人"><Input/></Form.Item><Form.Item name="count" label="人数"><Input/></Form.Item><Form.Item name="status" label="状态"><Select options={["启用","停用"].map(x=>({value:x,label:x}))}/></Form.Item></>:<><Form.Item name="role" label="角色名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="scope" label="数据范围"><Input/></Form.Item><Form.Item name="mods" label="模块权限"><Checkbox.Group options={modules}/></Form.Item></>}</Form></Modal>}
